#!/bin/sh
##Version##1.1##
PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/openerp-jasper/jasper-server.sh
NAME=openerp-jasper
DESC=openerp-jasper
USER=root

if [ -x ${DAEMON} ]
then
        echo 'Daemon exist'
else
        echo 'ERROR'
        exit 0
fi

# Include openerp-server defaults
# DAEMON_OPTS from the conf file
#. /etc/default/openerp_server.conf


case "${1}" in
	start)
		echo -n "Starting ${DESC}: "

		start-stop-daemon --start --quiet --pidfile /var/run/${NAME}.pid \
			--chuid ${USER} --background --make-pidfile \
			--exec ${DAEMON} -- ${DAEMON_OPTS}

		echo "${NAME}. $?"
		;;

	stop)
		echo -n "Stopping ${DESC}: "

		start-stop-daemon --stop --quiet --pidfile /var/run/${NAME}.pid \
			--oknodo

		ps aux | grep JasperServer | grep -v "grep" | awk '{print $2}' | xargs kill -9
		echo "${NAME}."
		;;

	restart|force-reload)
		echo -n "Restarting ${DESC}: "

		start-stop-daemon --stop --quiet --pidfile /var/run/${NAME}.pid \
			--oknodo

		sleep 1

		start-stop-daemon --start --quiet --pidfile /var/run/${NAME}.pid \
			--chuid ${USER} --background --make-pidfile \
			--exec ${DAEMON} -- ${DAEMON_OPTS}

		echo "${NAME}."
		;;

	*)
		N=/etc/init.d/${NAME}
		echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0
